name = "NODERegistry"
uuid = "b106cf6d-4dac-4130-88f6-627e12166377"
repo = "https://github.com/April-Hannah-Lena/Neural-ODE-Project-Registry.git"

[packages]
33d280d1-ac47-4b0f-9c2e-fa6a385d0226 = { name = "GAIO", path = "G/GAIO" }
56c15bac-5c7d-45b6-b0e6-74117a5d8120 = { name = "NODEData", path = "N/NODEData" }
c9c3e87f-99dd-4ea8-9de5-c6a08e86872f = { name = "ChaoticNDETools", path = "C/ChaoticNDETools" }
